### ISSUE TITLE
I get a divide by zero error when using the plugin

### ISSUE THREAD

**Issue by bgreman** [govau/cf-report-memory-usage#1]
We have a rather large CF footprint, with about 20 spaces across 3 orgs and hundreds of apps.

When I run the plugin, I get a long list of GET requests to the API, followed by:

```
panic: runtime error: integer divide by zero

goroutine 1 [running]:
main.(*reportMemoryUsage).reportMemoryUsage(0xaee8e0, 0xc0000f99e0, 0x84e620, 0xc00000e020, 0x0, 0x0, 0x3a)
        /home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/main-report-memory-usage.go:276 +0xbe3
main.(*reportMemoryUsage).Run(0xaee8e0, 0x853a20, 0xc00004bf60, 0xc0000100b0, 0x1, 0x1)
        /home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/main-report-memory-usage.go:175 +0x2bb
github.com/govau/cf-report-memory-usage/vendor/code.cloudfoundry.org/cli/plugin.Start(0x84fb40, 0xaee8e0)
        /home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/vendor/code.cloudfoundry.org/cli/plugin/plugin_shim.go:34 +0x284
main.main()
        /home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/main-report-memory-usage.go:339 +0x3d```

**Comment by aeijdenberg** [comment]
Apologies @bgreman - for some reason I didn't seem to get a notification when this issue was reported. I just found the issue and fixed it, and am cutting a new release now.

**Comment by aeijdenberg** [comment]
Fixed in https://github.com/govau/cf-report-memory-usage/commit/bb7159785f5a9be6c536ebc6acb0de8eabc6b2c1
