### ISSUE TITLE
Getting panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by arungskumar** [govau/cf-report-memory-usage#3]
panic: runtime error: integer divide by zero

goroutine 1 [running]:
main.(*reportMemoryUsage).reportMemoryUsage(0x1702578, 0xc00012cc30, 0x1459700, 0xc00000c018, 0x0, 0x0, 0x3a)
	/home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/main-report-memory-usage.go:276 +0xbe3
main.(*reportMemoryUsage).Run(0x1702578, 0x145ee60, 0xc00004ff40, 0xc00000e0e0, 0x1, 0x1)
	/home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/main-report-memory-usage.go:175 +0x2bb
github.com/govau/cf-report-memory-usage/vendor/code.cloudfoundry.org/cli/plugin.Start(0x145ada0, 0x1702578)
	/home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/vendor/code.cloudfoundry.org/cli/plugin/plugin_shim.go:34 +0x284
main.main()
	/home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/main-report-memory-usage.go:339 +0x3d

**Comment by srinivasanrk** [comment]
Getting the same error.

panic: runtime error: integer divide by zero

goroutine 1 [running]:
main.(*reportMemoryUsage).reportMemoryUsage(0xac3488, 0xc000111740, 0x839de0, 0xc000006018, 0x0, 0x0, 0x3a)
        /home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/main-report-memory-usage.go:276 +0xbea
main.(*reportMemoryUsage).Run(0xac3488, 0x83ee00, 0xc00010e220, 0xc000018160, 0x1, 0x2)
        /home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/main-report-memory-usage.go:175 +0x2c2
github.com/govau/cf-report-memory-usage/vendor/code.cloudfoundry.org/cli/plugin.Start(0x83b220, 0xac3488)
        /home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/vendor/code.cloudfoundry.org/cli/plugin/plugin_shim.go:34 +0x28b
main.main()
        /home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/main-report-memory-usage.go:339 +0x44

**Comment by abcbharath** [comment]
Getting the same error while generating the usage report

panic: runtime error: integer divide by zero

goroutine 1 [running]:
main.(*reportMemoryUsage).reportMemoryUsage(0x1702578, 0xc00010b290, 0x1459700, 0xc00008e008, 0x0, 0x0, 0x3a)
	/home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/main-report-memory-usage.go:276 +0xbe3
main.(*reportMemoryUsage).Run(0x1702578, 0x145ee60, 0xc00010e280, 0xc0000760b0, 0x1, 0x1)
	/home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/main-report-memory-usage.go:175 +0x2bb
github.com/govau/cf-report-memory-usage/vendor/code.cloudfoundry.org/cli/plugin.Start(0x145ada0, 0x1702578)
	/home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/vendor/code.cloudfoundry.org/cli/plugin/plugin_shim.go:34 +0x284
main.main()
	/home/aeijdenberg/go/src/github.com/govau/cf-report-memory-usage/main-report-memory-usage.go:339 +0x3d
